
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hirantha
 */
public class MainWindow extends javax.swing.JFrame {
    
    Connection dbcon;
    static String accessedUser;
    
    public MainWindow() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        showPanels();
        dbConnectr conn = new dbConnectr();
        dbcon = conn.Connect();
        System.out.println(accessedUser);
        grantAccess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgFin_addClient = new javax.swing.JDialog();
        jPanel19 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_dlgFin_addClient_Company = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_dlgFin_addClient_Address = new javax.swing.JTextArea();
        txt_dlgFin_addClient_tele1 = new javax.swing.JTextField();
        txt_dlgFin_addClient_email = new javax.swing.JTextField();
        txt_dlgFin_addClient_tele2 = new javax.swing.JTextField();
        btnfin_dlgAddClientAdd = new javax.swing.JButton();
        btnfin_dlgAddClientCancel = new javax.swing.JButton();
        Main = new javax.swing.JPanel();
        ButtonMenu = new javax.swing.JPanel();
        btnHospital = new javax.swing.JButton();
        btnPharmacy = new javax.swing.JButton();
        btnFinance = new javax.swing.JButton();
        btnPetshop = new javax.swing.JButton();
        btnHealthcare = new javax.swing.JButton();
        btnDaycare = new javax.swing.JButton();
        btnMobileService = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        Container = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnlPharmacy = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtItemcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnlHospital = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        pnlMobile = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        pnlPetshop = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        pnlDaycare = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pnlHealthcare = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        pnlEmployee = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        pnlFinance = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnlFinanceButtons = new javax.swing.JPanel();
        btnFinanceClients = new javax.swing.JButton();
        btnFinanceReports = new javax.swing.JButton();
        pnlFinanceClients = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_Fin_SearchCompany = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Fin_Client_Details = new javax.swing.JTable();
        btnFin_AddClient = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlFinanceReports = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        dlgFin_addClient.setTitle("Client Details");
        dlgFin_addClient.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 5));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("Company Name");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("Address");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Telephone #1");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Telephone #2");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setText("Email");

        txt_dlgFin_addClient_Company.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txt_dlgFin_addClient_Address.setColumns(20);
        txt_dlgFin_addClient_Address.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_dlgFin_addClient_Address.setRows(5);
        jScrollPane4.setViewportView(txt_dlgFin_addClient_Address);

        txt_dlgFin_addClient_tele1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txt_dlgFin_addClient_email.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txt_dlgFin_addClient_tele2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnfin_dlgAddClientAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clientok_x24.png"))); // NOI18N
        btnfin_dlgAddClientAdd.setText("Add");
        btnfin_dlgAddClientAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfin_dlgAddClientAddActionPerformed(evt);
            }
        });

        btnfin_dlgAddClientCancel.setText("Cancel");
        btnfin_dlgAddClientCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfin_dlgAddClientCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(btnfin_dlgAddClientCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnfin_dlgAddClientAdd))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(txt_dlgFin_addClient_tele1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txt_dlgFin_addClient_tele2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4)
                            .addComponent(txt_dlgFin_addClient_Company)
                            .addComponent(txt_dlgFin_addClient_email))))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_dlgFin_addClient_Company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dlgFin_addClient_tele1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_dlgFin_addClient_tele2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dlgFin_addClient_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(35, 35, 35)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfin_dlgAddClientAdd)
                    .addComponent(btnfin_dlgAddClientCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgFin_addClientLayout = new javax.swing.GroupLayout(dlgFin_addClient.getContentPane());
        dlgFin_addClient.getContentPane().setLayout(dlgFin_addClientLayout);
        dlgFin_addClientLayout.setHorizontalGroup(
            dlgFin_addClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgFin_addClientLayout.setVerticalGroup(
            dlgFin_addClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veterinary Hospital Management System");

        Main.setBackground(new java.awt.Color(57, 93, 120));

        ButtonMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        btnHospital.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/surgon_x32.png"))); // NOI18N
        btnHospital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 4));
        btnHospital.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnHospital.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHospital.setIconTextGap(15);
        btnHospital.setLabel("Hospital                  ");
        btnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalActionPerformed(evt);
            }
        });

        btnPharmacy.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnPharmacy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pharmacy_x32.png"))); // NOI18N
        btnPharmacy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 4));
        btnPharmacy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPharmacy.setIconTextGap(15);
        btnPharmacy.setLabel("Pharmacy               ");
        btnPharmacy.setOpaque(false);
        btnPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmacyActionPerformed(evt);
            }
        });

        btnFinance.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnFinance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money_x32.png"))); // NOI18N
        btnFinance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 4));
        btnFinance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnFinance.setIconTextGap(15);
        btnFinance.setLabel("Finance                   ");
        btnFinance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceActionPerformed(evt);
            }
        });

        btnPetshop.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnPetshop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shop2_x32.png"))); // NOI18N
        btnPetshop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 4));
        btnPetshop.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPetshop.setIconTextGap(15);
        btnPetshop.setLabel("Pet Shop                 ");
        btnPetshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetshopActionPerformed(evt);
            }
        });

        btnHealthcare.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnHealthcare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medical_32.png"))); // NOI18N
        btnHealthcare.setText("Health Care           ");
        btnHealthcare.setActionCommand("Health Care             ");
        btnHealthcare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 4));
        btnHealthcare.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnHealthcare.setIconTextGap(15);
        btnHealthcare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHealthcareActionPerformed(evt);
            }
        });

        btnDaycare.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnDaycare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/horse_x32.png"))); // NOI18N
        btnDaycare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 4));
        btnDaycare.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDaycare.setIconTextGap(15);
        btnDaycare.setLabel("Day Care                ");
        btnDaycare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaycareActionPerformed(evt);
            }
        });

        btnMobileService.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnMobileService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vehicle_x32.png"))); // NOI18N
        btnMobileService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 4));
        btnMobileService.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMobileService.setIconTextGap(15);
        btnMobileService.setLabel("Mobile Service      ");
        btnMobileService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobileServiceActionPerformed(evt);
            }
        });

        btnEmployee.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/boss_x32.png"))); // NOI18N
        btnEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 4));
        btnEmployee.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnEmployee.setIconTextGap(15);
        btnEmployee.setLabel("Employee               ");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("Log Out");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 4));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonMenuLayout = new javax.swing.GroupLayout(ButtonMenu);
        ButtonMenu.setLayout(ButtonMenuLayout);
        ButtonMenuLayout.setHorizontalGroup(
            ButtonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHealthcare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDaycare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPetshop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPharmacy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHospital, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMobileService, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinance, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ButtonMenuLayout.setVerticalGroup(
            ButtonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMobileService, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPetshop, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDaycare, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHealthcare, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinance, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnHospital.getAccessibleContext().setAccessibleName("Hospital");

        Container.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Veterinary Hospital (PVT) LTD");

        jLabel16.setText("testing dilankas git ok");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(484, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1)
                .addGap(114, 114, 114)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pharmacy & Shop", 0, 0, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printbill_x48.png"))); // NOI18N
        jButton1.setText("Print");

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 2));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("Add item");

        txtItemcode.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtItemcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemcodeKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Item Code :");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Quantity :");

        txtQuantity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItemcode, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemcode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 2));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/leftarrow_x32.png"))); // NOI18N
        jButton2.setToolTipText("Add to List");
        jButton2.setActionCommand("<<     Add");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash_x32.png"))); // NOI18N
        jButton3.setToolTipText("Remove Selected Item");

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 2));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel5.setText("Total");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel6.setText("Rs.");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("0.00");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Issue Bill", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stock", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout pnlPharmacyLayout = new javax.swing.GroupLayout(pnlPharmacy);
        pnlPharmacy.setLayout(pnlPharmacyLayout);
        pnlPharmacyLayout.setHorizontalGroup(
            pnlPharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPharmacyLayout.setVerticalGroup(
            pnlPharmacyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hospital Management", 0, 0, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Customer", jPanel4);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab2", jPanel12);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout pnlHospitalLayout = new javax.swing.GroupLayout(pnlHospital);
        pnlHospital.setLayout(pnlHospitalLayout);
        pnlHospitalLayout.setHorizontalGroup(
            pnlHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHospitalLayout.setVerticalGroup(
            pnlHospitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mobile Veterinary Service", 0, 0, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("New Job", jPanel13);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Search", jPanel16);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1113, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Vehicles", jPanel15);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        javax.swing.GroupLayout pnlMobileLayout = new javax.swing.GroupLayout(pnlMobile);
        pnlMobile.setLayout(pnlMobileLayout);
        pnlMobileLayout.setHorizontalGroup(
            pnlMobileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMobileLayout.setVerticalGroup(
            pnlMobileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pet Shop", 0, 0, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlPetshopLayout = new javax.swing.GroupLayout(pnlPetshop);
        pnlPetshop.setLayout(pnlPetshopLayout);
        pnlPetshopLayout.setHorizontalGroup(
            pnlPetshopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPetshopLayout.setVerticalGroup(
            pnlPetshopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pet DayCare", 0, 0, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDaycareLayout = new javax.swing.GroupLayout(pnlDaycare);
        pnlDaycare.setLayout(pnlDaycareLayout);
        pnlDaycareLayout.setHorizontalGroup(
            pnlDaycareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDaycareLayout.setVerticalGroup(
            pnlDaycareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pet Health Care Service", 0, 0, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlHealthcareLayout = new javax.swing.GroupLayout(pnlHealthcare);
        pnlHealthcare.setLayout(pnlHealthcareLayout);
        pnlHealthcareLayout.setHorizontalGroup(
            pnlHealthcareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHealthcareLayout.setVerticalGroup(
            pnlHealthcareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Management", 0, 0, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlEmployeeLayout = new javax.swing.GroupLayout(pnlEmployee);
        pnlEmployee.setLayout(pnlEmployeeLayout);
        pnlEmployeeLayout.setHorizontalGroup(
            pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlEmployeeLayout.setVerticalGroup(
            pnlEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Finance Management", 0, 0, new java.awt.Font("Calibri", 0, 18))); // NOI18N

        pnlFinanceButtons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 2));

        btnFinanceClients.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnFinanceClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clients_x32.png"))); // NOI18N
        btnFinanceClients.setText("Clients");
        btnFinanceClients.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinanceClients.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFinanceClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceClientsActionPerformed(evt);
            }
        });

        btnFinanceReports.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnFinanceReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reports_x32.png"))); // NOI18N
        btnFinanceReports.setText("Reports");
        btnFinanceReports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFinanceReports.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFinanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFinanceButtonsLayout = new javax.swing.GroupLayout(pnlFinanceButtons);
        pnlFinanceButtons.setLayout(pnlFinanceButtonsLayout);
        pnlFinanceButtonsLayout.setHorizontalGroup(
            pnlFinanceButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinanceButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinanceClients, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinanceReports)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFinanceButtonsLayout.setVerticalGroup(
            pnlFinanceButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinanceButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinanceButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinanceClients, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnFinanceReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlFinanceClients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 2));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Search");

        txt_Fin_SearchCompany.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txt_Fin_SearchCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Fin_SearchCompanyKeyReleased(evt);
            }
        });

        tbl_Fin_Client_Details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ClientID", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Fin_Client_Details);

        btnFin_AddClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addclient_x24.png"))); // NOI18N
        btnFin_AddClient.setToolTipText("Add New Client");
        btnFin_AddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFin_AddClientActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editclient_x24.png"))); // NOI18N
        jButton12.setToolTipText("Edit Selected Client");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/removeclient_x24.png"))); // NOI18N
        jButton13.setToolTipText("Remove Selected Client");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel9.setText("Client Details");

        jLabel10.setText("Product Details");

        javax.swing.GroupLayout pnlFinanceClientsLayout = new javax.swing.GroupLayout(pnlFinanceClients);
        pnlFinanceClients.setLayout(pnlFinanceClientsLayout);
        pnlFinanceClientsLayout.setHorizontalGroup(
            pnlFinanceClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinanceClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinanceClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlFinanceClientsLayout.createSequentialGroup()
                        .addGroup(pnlFinanceClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFinanceClientsLayout.createSequentialGroup()
                                .addComponent(btnFin_AddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFinanceClientsLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Fin_SearchCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFinanceClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFinanceClientsLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlFinanceClientsLayout.setVerticalGroup(
            pnlFinanceClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinanceClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinanceClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_Fin_SearchCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFinanceClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFinanceClientsLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE))
                    .addGroup(pnlFinanceClientsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addGroup(pnlFinanceClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFin_AddClient)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addContainerGap())
        );

        pnlFinanceReports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(57, 93, 120), 2));

        javax.swing.GroupLayout pnlFinanceReportsLayout = new javax.swing.GroupLayout(pnlFinanceReports);
        pnlFinanceReports.setLayout(pnlFinanceReportsLayout);
        pnlFinanceReportsLayout.setHorizontalGroup(
            pnlFinanceReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2394, Short.MAX_VALUE)
        );
        pnlFinanceReportsLayout.setVerticalGroup(
            pnlFinanceReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlFinanceClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFinanceButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlFinanceReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(pnlFinanceButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFinanceClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(pnlFinanceReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlFinanceLayout = new javax.swing.GroupLayout(pnlFinance);
        pnlFinance.setLayout(pnlFinanceLayout);
        pnlFinanceLayout.setHorizontalGroup(
            pnlFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlFinanceLayout.setVerticalGroup(
            pnlFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFinance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHealthcare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlDaycare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlPetshop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlPharmacy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFinance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHealthcare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlDaycare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlPetshop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlPharmacy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmacyActionPerformed
        this.pnlPharmacy.setVisible(true);
        this.pnlHospital.setVisible(false);
        this.pnlMobile.setVisible(false);
        this.pnlPetshop.setVisible(false);
        this.pnlDaycare.setVisible(false);
        this.pnlHealthcare.setVisible(false);
        this.pnlEmployee.setVisible(false);
        this.pnlFinance.setVisible(false);
        this.pnlHome.setVisible(false);
        this.txtItemcode.requestFocusInWindow();
    }//GEN-LAST:event_btnPharmacyActionPerformed

    private void btnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalActionPerformed
        this.pnlPharmacy.setVisible(false);
        this.pnlHospital.setVisible(true);
        this.pnlMobile.setVisible(false);
        this.pnlPetshop.setVisible(false);
        this.pnlDaycare.setVisible(false);
        this.pnlHealthcare.setVisible(false);
        this.pnlEmployee.setVisible(false);
        this.pnlFinance.setVisible(false);
        this.pnlHome.setVisible(false);
    }//GEN-LAST:event_btnHospitalActionPerformed

    private void btnMobileServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobileServiceActionPerformed
        this.pnlPharmacy.setVisible(false);
        this.pnlHospital.setVisible(false);
        this.pnlMobile.setVisible(true);
        this.pnlPetshop.setVisible(false);
        this.pnlDaycare.setVisible(false);
        this.pnlHealthcare.setVisible(false);
        this.pnlEmployee.setVisible(false);
        this.pnlFinance.setVisible(false);
        this.pnlHome.setVisible(false);
    }//GEN-LAST:event_btnMobileServiceActionPerformed

    private void btnPetshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetshopActionPerformed
        this.pnlPharmacy.setVisible(false);
        this.pnlHospital.setVisible(false);
        this.pnlMobile.setVisible(false);
        this.pnlPetshop.setVisible(true);
        this.pnlDaycare.setVisible(false);
        this.pnlHealthcare.setVisible(false);
        this.pnlEmployee.setVisible(false);
        this.pnlFinance.setVisible(false);
        this.pnlHome.setVisible(false);
    }//GEN-LAST:event_btnPetshopActionPerformed

    private void btnDaycareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaycareActionPerformed
        this.pnlPharmacy.setVisible(false);
        this.pnlHospital.setVisible(false);
        this.pnlMobile.setVisible(false);
        this.pnlPetshop.setVisible(false);
        this.pnlDaycare.setVisible(true);
        this.pnlHealthcare.setVisible(false);
        this.pnlEmployee.setVisible(false);
        this.pnlFinance.setVisible(false);
        this.pnlHome.setVisible(false);
    }//GEN-LAST:event_btnDaycareActionPerformed

    private void btnHealthcareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHealthcareActionPerformed
        this.pnlPharmacy.setVisible(false);
        this.pnlHospital.setVisible(false);
        this.pnlMobile.setVisible(false);
        this.pnlPetshop.setVisible(false);
        this.pnlDaycare.setVisible(false);
        this.pnlHealthcare.setVisible(true);
        this.pnlEmployee.setVisible(false);
        this.pnlFinance.setVisible(false);
        this.pnlHome.setVisible(false);
    }//GEN-LAST:event_btnHealthcareActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        this.pnlPharmacy.setVisible(false);
        this.pnlHospital.setVisible(false);
        this.pnlMobile.setVisible(false);
        this.pnlPetshop.setVisible(false);
        this.pnlDaycare.setVisible(false);
        this.pnlHealthcare.setVisible(false);
        this.pnlEmployee.setVisible(true);
        this.pnlFinance.setVisible(false);
        this.pnlHome.setVisible(false);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnFinanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceActionPerformed
        this.pnlPharmacy.setVisible(false);
        this.pnlHospital.setVisible(false);
        this.pnlMobile.setVisible(false);
        this.pnlPetshop.setVisible(false);
        this.pnlDaycare.setVisible(false);
        this.pnlHealthcare.setVisible(false);
        this.pnlEmployee.setVisible(false);
        this.pnlFinance.setVisible(true);
        this.pnlHome.setVisible(false);
        
        //---------filling client details table-----------------
            update_tbl_Fin_Client_Details();
        //------------------------------------------------------
    }//GEN-LAST:event_btnFinanceActionPerformed

    private void txtItemcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemcodeKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.txtQuantity.requestFocus();
        }
    }//GEN-LAST:event_txtItemcodeKeyPressed

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            this.txtItemcode.setText("");
            this.txtQuantity.setText("");
            this.txtItemcode.requestFocus();
        }
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        this.txtItemcode.requestFocusInWindow();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnFinanceClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceClientsActionPerformed
        this.pnlFinanceClients.setVisible(true);
        this.pnlFinanceReports.setVisible(false);
        update_tbl_Fin_Client_Details();
    }//GEN-LAST:event_btnFinanceClientsActionPerformed

    private void btnFinanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceReportsActionPerformed
        this.pnlFinanceReports.setVisible(true);
        this.pnlFinanceClients.setVisible(false);   
    }//GEN-LAST:event_btnFinanceReportsActionPerformed

    private void btnFin_AddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFin_AddClientActionPerformed
        //----Clear textfields-------------------------------
        this.txt_dlgFin_addClient_Company.setText("");
        this.txt_dlgFin_addClient_Address.setText("");
        this.txt_dlgFin_addClient_tele1.setText("");
        this.txt_dlgFin_addClient_tele2.setText("");
        this.txt_dlgFin_addClient_email.setText("");
        //---------------------------------------------------
        this.dlgFin_addClient.setSize(650,420);
        this.dlgFin_addClient.setTitle("Client Details");   
        this.dlgFin_addClient.setLocationRelativeTo(this);
        this.dlgFin_addClient.setVisible(true); 
    }//GEN-LAST:event_btnFin_AddClientActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int userChoice=JOptionPane.showConfirmDialog(this, "Are you sure?","Log out",JOptionPane.YES_NO_OPTION);
        
        if(userChoice==0){
            LoginWindow lw = new LoginWindow();
            lw.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnfin_dlgAddClientCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfin_dlgAddClientCancelActionPerformed
        this.dlgFin_addClient.dispose();
    }//GEN-LAST:event_btnfin_dlgAddClientCancelActionPerformed

    private void btnfin_dlgAddClientAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfin_dlgAddClientAddActionPerformed
        String company = this.txt_dlgFin_addClient_Company.getText();
        String address = this.txt_dlgFin_addClient_Address.getText();
        String tele1 = this.txt_dlgFin_addClient_tele1.getText();
        String tele2 = this.txt_dlgFin_addClient_tele2.getText();
        String email = this.txt_dlgFin_addClient_email.getText();
        
        try{
            String SQL = "insert into finance_clients (clientID,company_name,address,tele1,tele2,email) values(?,?,?,?,?,?)";
            PreparedStatement pst = dbcon.prepareStatement(SQL);
            pst.setString(1, generateClientID());
            pst.setString(2, company);
            pst.setString(3, address);
            pst.setString(4, tele1);
            pst.setString(5, tele2);
            pst.setString(6, email);
            pst.execute();
            increaseNoClientsByOne();
            JOptionPane.showMessageDialog(dlgFin_addClient, "Client added Successfully!","Client Details",JOptionPane.INFORMATION_MESSAGE);
            update_tbl_Fin_Client_Details();
            this.dlgFin_addClient.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(dlgFin_addClient, "Client adding failed!","Database Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnfin_dlgAddClientAddActionPerformed

    private void txt_Fin_SearchCompanyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Fin_SearchCompanyKeyReleased
        String company=null;
        company=this.txt_Fin_SearchCompany.getText();
        String sql = "select clientID as 'ClientID',company_name as 'Company', address as 'Address', tele1 as 'Telephone #1', tele2 as 'Telephone #2', email as 'Email' from finance_clients where company_name like '%"+company+"%'";
        try{
            Statement stmnt = dbcon.createStatement();
            ResultSet rs_Client_Details = stmnt.executeQuery(sql);
            this.tbl_Fin_Client_Details.setModel(DbUtils.resultSetToTableModel(rs_Client_Details));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Cannot Refresh Client Details!","Database Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_Fin_SearchCompanyKeyReleased
    
    public void showPanels(){
        this.pnlHome.setVisible(true);
        this.pnlPharmacy.setVisible(false);
        this.pnlHospital.setVisible(false);
        this.pnlMobile.setVisible(false);
        this.pnlPetshop.setVisible(false);
        this.pnlDaycare.setVisible(false);
        this.pnlHealthcare.setVisible(false);
        this.pnlEmployee.setVisible(false);
        this.pnlFinance.setVisible(false);  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    public void grantAccess(){
        try{
            Statement stmnt = dbcon.createStatement();
            ResultSet rs = stmnt.executeQuery("select * from access_info where userID='"+accessedUser+"'");
            
            while(rs.next()){
                if(rs.getBoolean("accessPh")){
                    this.btnPharmacy.setEnabled(true);
                }
                else{
                    this.btnPharmacy.setEnabled(false);
                }
                if(rs.getBoolean("accessHos")){
                    this.btnHospital.setEnabled(true);
                }
                else{
                    this.btnHospital.setEnabled(false);
                }
                if(rs.getBoolean("accessMVS")){
                    this.btnMobileService.setEnabled(true);
                }
                else{
                    this.btnMobileService.setEnabled(false);
                }
                if(rs.getBoolean("accessPS")){
                    this.btnPetshop.setEnabled(true);
                }
                else{
                    this.btnPetshop.setEnabled(false);
                }
                if(rs.getBoolean("accessDC")){
                    this.btnDaycare.setEnabled(true);
                }
                else{
                    this.btnDaycare.setEnabled(false);
                }
                if(rs.getBoolean("accessHC")){
                    this.btnHealthcare.setEnabled(true);
                }
                else{
                    this.btnHealthcare.setEnabled(false);
                }
                if(rs.getBoolean("accessEmp")){
                    this.btnEmployee.setEnabled(true);
                }
                else{
                    this.btnEmployee.setEnabled(false);
                }
                if(rs.getBoolean("accessFin")){
                    this.btnFinance.setEnabled(true);
                }
                else{
                    this.btnFinance.setEnabled(false);
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public String generateClientID(){
        String prefix="CL";
        int noClients=0;
        String clientID=null;
        try{
            Statement stmnt = dbcon.createStatement();
            ResultSet rs = stmnt.executeQuery("select fclients from count");
            while(rs.next()){
                noClients = rs.getInt("fclients");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        if(noClients<9){
            clientID=prefix.concat("000").concat(Integer.toString(noClients+1));
            return clientID;
        }
        else if(noClients<99){
            clientID=prefix.concat("00").concat(Integer.toString(noClients+1));
            return clientID;
        }
        else if(noClients<999){
            clientID=prefix.concat("0").concat(Integer.toString(noClients+1));
            return clientID;
        }
        else if(noClients<9999){
            clientID=prefix.concat(Integer.toString(noClients+1));
            return clientID;
        }
        else{
            JOptionPane.showMessageDialog(dlgFin_addClient, "Cannot Generate ClientID. Maximum no.of Clients Reached","Database Error",JOptionPane.ERROR_MESSAGE);
            return clientID;
        }
    }
    
    public void increaseNoClientsByOne(){
        try{
            int noClients=0;
            Statement stmnt = dbcon.createStatement();
            ResultSet rs = stmnt.executeQuery("select fclients from count");
            while(rs.next()){
                noClients = rs.getInt("fclients");
            }
            try{
                String SQL = "update count set fclients="+(noClients+1)+" where fclients="+noClients;
                Statement stmnt2 = dbcon.createStatement();
                stmnt2.executeUpdate(SQL);
            }
            catch(Exception ex){
                ex.printStackTrace();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void update_tbl_Fin_Client_Details(){
        String sql = "select clientID as 'ClientID',company_name as 'Company', address as 'Address', tele1 as 'Telephone #1', tele2 as 'Telephone #2', email as 'Email' from finance_clients";
        try{
            Statement stmnt = dbcon.createStatement();
            ResultSet rs_Client_Details = stmnt.executeQuery(sql);
            this.tbl_Fin_Client_Details.setModel(DbUtils.resultSetToTableModel(rs_Client_Details));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(dlgFin_addClient, "Cannot Refresh Client Details!","Database Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonMenu;
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Main;
    private javax.swing.JButton btnDaycare;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnFin_AddClient;
    private javax.swing.JButton btnFinance;
    private javax.swing.JButton btnFinanceClients;
    private javax.swing.JButton btnFinanceReports;
    private javax.swing.JButton btnHealthcare;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMobileService;
    private javax.swing.JButton btnPetshop;
    private javax.swing.JButton btnPharmacy;
    private javax.swing.JButton btnfin_dlgAddClientAdd;
    private javax.swing.JButton btnfin_dlgAddClientCancel;
    private javax.swing.JDialog dlgFin_addClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel pnlDaycare;
    private javax.swing.JPanel pnlEmployee;
    private javax.swing.JPanel pnlFinance;
    private javax.swing.JPanel pnlFinanceButtons;
    private javax.swing.JPanel pnlFinanceClients;
    private javax.swing.JPanel pnlFinanceReports;
    private javax.swing.JPanel pnlHealthcare;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlHospital;
    private javax.swing.JPanel pnlMobile;
    private javax.swing.JPanel pnlPetshop;
    private javax.swing.JPanel pnlPharmacy;
    private javax.swing.JTable tbl_Fin_Client_Details;
    private javax.swing.JTextField txtItemcode;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txt_Fin_SearchCompany;
    private javax.swing.JTextArea txt_dlgFin_addClient_Address;
    private javax.swing.JTextField txt_dlgFin_addClient_Company;
    private javax.swing.JTextField txt_dlgFin_addClient_email;
    private javax.swing.JTextField txt_dlgFin_addClient_tele1;
    private javax.swing.JTextField txt_dlgFin_addClient_tele2;
    // End of variables declaration//GEN-END:variables
}
